@host = localhost
@port = 8080

###
# @name getVersion
# 获取maa版本号
GET http://{{host}}:{{port}}/version
Accept: application/json

###
# @name getMaaConnected
# 获取MAA是否连接
GET http://{{host}}:{{port}}/maa/connected
Accept: application/json

###
# @name getConnectConf
# 获取连接配置
GET http://{{host}}:{{port}}/maa/connectConf
Accept: application/json

###
# @name postConnectConf
# 保存连接配置
POST http://{{host}}:{{port}}/maa/connectConf
Accept: application/json
Content-Type: application/json

{
    "address":"192.168.123.234:5555",
    "adbPath":"/usr/bin/adb"
}

###
# @name doTestConnect
# 测试连接配置
POST http://{{host}}:{{port}}/maa/testConnect
Accept: application/json
Content-Type: application/json

{
    "address":"192.168.123.234:5555",
    "adbPath":"/usr/bin/adb",
    "config":"CompatPOSIXShell"
}