name: Dependabot Placeholder Check

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

# Minimal permissions
permissions:
  contents: read
  pull-requests: read

jobs:
  placeholder-check:
    name: Dependabot PR Placeholder
    runs-on: ubuntu-latest
    
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Basic validation
        run: |
          echo "🤖 Dependabot PR detected"
          echo "📋 PR Number: ${{ github.event.number }}"
          echo "👤 Author: ${{ github.actor }}"
          echo "🌿 Branch: ${{ github.head_ref }}"
          echo "🎯 Target: ${{ github.base_ref }}"

      - name: Validate PR structure
        run: |
          echo "✅ Basic validation completed"
          echo "🚀 Ready for auto-merge evaluation"

      - name: Set status
        run: |
          echo "placeholder_check=completed" >> $GITHUB_OUTPUT
          echo "✅ Placeholder check completed successfully"
